/***************************************************
 * Generated by SVG Artista on 4/5/2022, 1:28:08 PM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/

@-webkit-keyframes animate-svg-stroke-1 {
  0% {
    stroke-dashoffset: 81.66297912597656px;
    stroke-dasharray: 81.66297912597656px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 81.66297912597656px;
  }
}

@keyframes animate-svg-stroke-1 {
  0% {
    stroke-dashoffset: 81.66297912597656px;
    stroke-dasharray: 81.66297912597656px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 81.66297912597656px;
  }
}

@-webkit-keyframes animate-svg-fill-1 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

@keyframes animate-svg-fill-1 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

.svg-elem-1 {
  -webkit-animation: animate-svg-stroke-1 5s linear 0s both, animate-svg-fill-1 1s ease 0.8s both;
          animation: animate-svg-stroke-1 5s linear 0s both, animate-svg-fill-1 1s ease 0.8s both;
}

@-webkit-keyframes animate-svg-stroke-2 {
  0% {
    stroke-dashoffset: 630.0419921875px;
    stroke-dasharray: 630.0419921875px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 630.0419921875px;
  }
}

@keyframes animate-svg-stroke-2 {
  0% {
    stroke-dashoffset: 630.0419921875px;
    stroke-dasharray: 630.0419921875px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 630.0419921875px;
  }
}

@-webkit-keyframes animate-svg-fill-2 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(1, 2, 2);
  }
}

@keyframes animate-svg-fill-2 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(1, 2, 2);
  }
}

.svg-elem-2 {
  -webkit-animation: animate-svg-stroke-2 5s linear 0.12s both, animate-svg-fill-2 1s ease 0.9s both;
          animation: animate-svg-stroke-2 5s linear 0.12s both, animate-svg-fill-2 1s ease 0.9s both;
}

@-webkit-keyframes animate-svg-stroke-3 {
  0% {
    stroke-dashoffset: 920.6058959960938px;
    stroke-dasharray: 920.6058959960938px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 920.6058959960938px;
  }
}

@keyframes animate-svg-stroke-3 {
  0% {
    stroke-dashoffset: 920.6058959960938px;
    stroke-dasharray: 920.6058959960938px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 920.6058959960938px;
  }
}

@-webkit-keyframes animate-svg-fill-3 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(1, 2, 2);
  }
}

@keyframes animate-svg-fill-3 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(1, 2, 2);
  }
}

.svg-elem-3 {
  -webkit-animation: animate-svg-stroke-3 5s linear 0.24s both, animate-svg-fill-3 1s ease 1s both;
          animation: animate-svg-stroke-3 5s linear 0.24s both, animate-svg-fill-3 1s ease 1s both;
}

@-webkit-keyframes animate-svg-stroke-4 {
  0% {
    stroke-dashoffset: 674.4476318359375px;
    stroke-dasharray: 674.4476318359375px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 674.4476318359375px;
  }
}

@keyframes animate-svg-stroke-4 {
  0% {
    stroke-dashoffset: 674.4476318359375px;
    stroke-dasharray: 674.4476318359375px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 674.4476318359375px;
  }
}

@-webkit-keyframes animate-svg-fill-4 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(1, 2, 2);
  }
}

@keyframes animate-svg-fill-4 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(1, 2, 2);
  }
}

.svg-elem-4 {
  -webkit-animation: animate-svg-stroke-4 5s linear 0.36s both, animate-svg-fill-4 1s ease 1.1s both;
          animation: animate-svg-stroke-4 5s linear 0.36s both, animate-svg-fill-4 1s ease 1.1s both;
}

@-webkit-keyframes animate-svg-stroke-5 {
  0% {
    stroke-dashoffset: 1196.9527587890625px;
    stroke-dasharray: 1196.9527587890625px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 1196.9527587890625px;
  }
}

@keyframes animate-svg-stroke-5 {
  0% {
    stroke-dashoffset: 1196.9527587890625px;
    stroke-dasharray: 1196.9527587890625px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 1196.9527587890625px;
  }
}

@-webkit-keyframes animate-svg-fill-5 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(1, 2, 2);
  }
}

@keyframes animate-svg-fill-5 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(1, 2, 2);
  }
}

.svg-elem-5 {
  -webkit-animation: animate-svg-stroke-5 5s linear 0.48s both,
                       animate-svg-fill-5 1s ease 1.2000000000000002s both;
          animation: animate-svg-stroke-5 5s linear 0.48s both,
               animate-svg-fill-5 1s ease 1.2000000000000002s both;
}

@-webkit-keyframes animate-svg-stroke-6 {
  0% {
    stroke-dashoffset: 868.9707641601562px;
    stroke-dasharray: 868.9707641601562px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 868.9707641601562px;
  }
}

@keyframes animate-svg-stroke-6 {
  0% {
    stroke-dashoffset: 868.9707641601562px;
    stroke-dasharray: 868.9707641601562px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 868.9707641601562px;
  }
}

@-webkit-keyframes animate-svg-fill-6 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(1, 2, 2);
  }
}

@keyframes animate-svg-fill-6 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(1, 2, 2);
  }
}

.svg-elem-6 {
  -webkit-animation: animate-svg-stroke-6 5s linear 0.6s both, animate-svg-fill-6 1s ease 1.3s both;
          animation: animate-svg-stroke-6 5s linear 0.6s both, animate-svg-fill-6 1s ease 1.3s both;
}

@-webkit-keyframes animate-svg-stroke-7 {
  0% {
    stroke-dashoffset: 506.5279235839844px;
    stroke-dasharray: 506.5279235839844px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 506.5279235839844px;
  }
}

@keyframes animate-svg-stroke-7 {
  0% {
    stroke-dashoffset: 506.5279235839844px;
    stroke-dasharray: 506.5279235839844px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 506.5279235839844px;
  }
}

@-webkit-keyframes animate-svg-fill-7 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(1, 2, 2);
  }
}

@keyframes animate-svg-fill-7 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(1, 2, 2);
  }
}

.svg-elem-7 {
  -webkit-animation: animate-svg-stroke-7 5s linear 0.72s both,
                       animate-svg-fill-7 1s ease 1.4000000000000001s both;
          animation: animate-svg-stroke-7 5s linear 0.72s both,
               animate-svg-fill-7 1s ease 1.4000000000000001s both;
}

@-webkit-keyframes animate-svg-stroke-8 {
  0% {
    stroke-dashoffset: 1011.0098876953125px;
    stroke-dasharray: 1011.0098876953125px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 1011.0098876953125px;
  }
}

@keyframes animate-svg-stroke-8 {
  0% {
    stroke-dashoffset: 1011.0098876953125px;
    stroke-dasharray: 1011.0098876953125px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 1011.0098876953125px;
  }
}

@-webkit-keyframes animate-svg-fill-8 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

@keyframes animate-svg-fill-8 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

.svg-elem-8 {
  -webkit-animation: animate-svg-stroke-8 5s linear 0.84s both, animate-svg-fill-8 1s ease 1.5s both;
          animation: animate-svg-stroke-8 5s linear 0.84s both, animate-svg-fill-8 1s ease 1.5s both;
}

@-webkit-keyframes animate-svg-stroke-9 {
  0% {
    stroke-dashoffset: 529.1154174804688px;
    stroke-dasharray: 529.1154174804688px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 529.1154174804688px;
  }
}

@keyframes animate-svg-stroke-9 {
  0% {
    stroke-dashoffset: 529.1154174804688px;
    stroke-dasharray: 529.1154174804688px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 529.1154174804688px;
  }
}

@-webkit-keyframes animate-svg-fill-9 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(1, 2, 2);
  }
}

@keyframes animate-svg-fill-9 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(1, 2, 2);
  }
}

.svg-elem-9 {
  -webkit-animation: animate-svg-stroke-9 5s linear 0.96s both, animate-svg-fill-9 1s ease 1.6s both;
          animation: animate-svg-stroke-9 5s linear 0.96s both, animate-svg-fill-9 1s ease 1.6s both;
}

@-webkit-keyframes animate-svg-stroke-10 {
  0% {
    stroke-dashoffset: 1055.8487548828125px;
    stroke-dasharray: 1055.8487548828125px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 1055.8487548828125px;
  }
}

@keyframes animate-svg-stroke-10 {
  0% {
    stroke-dashoffset: 1055.8487548828125px;
    stroke-dasharray: 1055.8487548828125px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 1055.8487548828125px;
  }
}

@-webkit-keyframes animate-svg-fill-10 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

@keyframes animate-svg-fill-10 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

.svg-elem-10 {
  -webkit-animation: animate-svg-stroke-10 5s linear 1.08s both,
                       animate-svg-fill-10 1s ease 1.7000000000000002s both;
          animation: animate-svg-stroke-10 5s linear 1.08s both,
               animate-svg-fill-10 1s ease 1.7000000000000002s both;
}

@-webkit-keyframes animate-svg-stroke-11 {
  0% {
    stroke-dashoffset: 3136.010986328125px;
    stroke-dasharray: 3136.010986328125px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 3136.010986328125px;
  }
}

@keyframes animate-svg-stroke-11 {
  0% {
    stroke-dashoffset: 3136.010986328125px;
    stroke-dasharray: 3136.010986328125px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 3136.010986328125px;
  }
}

@-webkit-keyframes animate-svg-fill-11 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(1, 2, 2);
  }
}

@keyframes animate-svg-fill-11 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(1, 2, 2);
  }
}

.svg-elem-11 {
  -webkit-animation: animate-svg-stroke-11 5s linear 1.2s both, animate-svg-fill-11 1s ease 1.8s both;
          animation: animate-svg-stroke-11 5s linear 1.2s both, animate-svg-fill-11 1s ease 1.8s both;
}

@-webkit-keyframes animate-svg-stroke-12 {
  0% {
    stroke-dashoffset: 908.2379150390625px;
    stroke-dasharray: 908.2379150390625px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 908.2379150390625px;
  }
}

@keyframes animate-svg-stroke-12 {
  0% {
    stroke-dashoffset: 908.2379150390625px;
    stroke-dasharray: 908.2379150390625px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 908.2379150390625px;
  }
}

@-webkit-keyframes animate-svg-fill-12 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(1, 2, 2);
  }
}

@keyframes animate-svg-fill-12 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(1, 2, 2);
  }
}

.svg-elem-12 {
  -webkit-animation: animate-svg-stroke-12 5s linear 1.3199999999999998s both,
                       animate-svg-fill-12 1s ease 1.9000000000000001s both;
          animation: animate-svg-stroke-12 5s linear 1.3199999999999998s both,
               animate-svg-fill-12 1s ease 1.9000000000000001s both;
}

@-webkit-keyframes animate-svg-stroke-13 {
  0% {
    stroke-dashoffset: 1690.69482421875px;
    stroke-dasharray: 1690.69482421875px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 1690.69482421875px;
  }
}

@keyframes animate-svg-stroke-13 {
  0% {
    stroke-dashoffset: 1690.69482421875px;
    stroke-dasharray: 1690.69482421875px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 1690.69482421875px;
  }
}

@-webkit-keyframes animate-svg-fill-13 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(1, 2, 2);
  }
}

@keyframes animate-svg-fill-13 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(1, 2, 2);
  }
}

.svg-elem-13 {
  -webkit-animation: animate-svg-stroke-13 5s linear 1.44s both, animate-svg-fill-13 1s ease 2s both;
          animation: animate-svg-stroke-13 5s linear 1.44s both, animate-svg-fill-13 1s ease 2s both;
}

@-webkit-keyframes animate-svg-stroke-14 {
  0% {
    stroke-dashoffset: 1575.193115234375px;
    stroke-dasharray: 1575.193115234375px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 1575.193115234375px;
  }
}

@keyframes animate-svg-stroke-14 {
  0% {
    stroke-dashoffset: 1575.193115234375px;
    stroke-dasharray: 1575.193115234375px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 1575.193115234375px;
  }
}

@-webkit-keyframes animate-svg-fill-14 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(1, 2, 2);
  }
}

@keyframes animate-svg-fill-14 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(1, 2, 2);
  }
}

.svg-elem-14 {
  -webkit-animation: animate-svg-stroke-14 5s linear 1.56s both,
                       animate-svg-fill-14 1s ease 2.1s both;
          animation: animate-svg-stroke-14 5s linear 1.56s both,
               animate-svg-fill-14 1s ease 2.1s both;
}

@-webkit-keyframes animate-svg-stroke-15 {
  0% {
    stroke-dashoffset: 1876.730224609375px;
    stroke-dasharray: 1876.730224609375px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 1876.730224609375px;
  }
}

@keyframes animate-svg-stroke-15 {
  0% {
    stroke-dashoffset: 1876.730224609375px;
    stroke-dasharray: 1876.730224609375px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 1876.730224609375px;
  }
}

@-webkit-keyframes animate-svg-fill-15 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(1, 2, 2);
  }
}

@keyframes animate-svg-fill-15 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(1, 2, 2);
  }
}

.svg-elem-15 {
  -webkit-animation: animate-svg-stroke-15 5s linear 1.68s both,
                       animate-svg-fill-15 1s ease 2.2s both;
          animation: animate-svg-stroke-15 5s linear 1.68s both,
               animate-svg-fill-15 1s ease 2.2s both;
}

@-webkit-keyframes animate-svg-stroke-16 {
  0% {
    stroke-dashoffset: 3736.488525390625px;
    stroke-dasharray: 3736.488525390625px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 3736.488525390625px;
  }
}

@keyframes animate-svg-stroke-16 {
  0% {
    stroke-dashoffset: 3736.488525390625px;
    stroke-dasharray: 3736.488525390625px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 3736.488525390625px;
  }
}

@-webkit-keyframes animate-svg-fill-16 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(1, 2, 2);
  }
}

@keyframes animate-svg-fill-16 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(1, 2, 2);
  }
}

.svg-elem-16 {
  -webkit-animation: animate-svg-stroke-16 5s linear 1.7999999999999998s both,
                       animate-svg-fill-16 1s ease 2.3s both;
          animation: animate-svg-stroke-16 5s linear 1.7999999999999998s both,
               animate-svg-fill-16 1s ease 2.3s both;
}

@-webkit-keyframes animate-svg-stroke-17 {
  0% {
    stroke-dashoffset: 351.9836730957031px;
    stroke-dasharray: 351.9836730957031px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 351.9836730957031px;
  }
}

@keyframes animate-svg-stroke-17 {
  0% {
    stroke-dashoffset: 351.9836730957031px;
    stroke-dasharray: 351.9836730957031px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 351.9836730957031px;
  }
}

@-webkit-keyframes animate-svg-fill-17 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

@keyframes animate-svg-fill-17 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

.svg-elem-17 {
  -webkit-animation: animate-svg-stroke-17 5s linear 1.92s both,
                       animate-svg-fill-17 1s ease 2.4000000000000004s both;
          animation: animate-svg-stroke-17 5s linear 1.92s both,
               animate-svg-fill-17 1s ease 2.4000000000000004s both;
}

@-webkit-keyframes animate-svg-stroke-18 {
  0% {
    stroke-dashoffset: 351.98382568359375px;
    stroke-dasharray: 351.98382568359375px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 351.98382568359375px;
  }
}

@keyframes animate-svg-stroke-18 {
  0% {
    stroke-dashoffset: 351.98382568359375px;
    stroke-dasharray: 351.98382568359375px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 351.98382568359375px;
  }
}

@-webkit-keyframes animate-svg-fill-18 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

@keyframes animate-svg-fill-18 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

.svg-elem-18 {
  -webkit-animation: animate-svg-stroke-18 5s linear 2.04s both,
                       animate-svg-fill-18 1s ease 2.5s both;
          animation: animate-svg-stroke-18 5s linear 2.04s both,
               animate-svg-fill-18 1s ease 2.5s both;
}

@-webkit-keyframes animate-svg-stroke-19 {
  0% {
    stroke-dashoffset: 315.7469787597656px;
    stroke-dasharray: 315.7469787597656px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 315.7469787597656px;
  }
}

@keyframes animate-svg-stroke-19 {
  0% {
    stroke-dashoffset: 315.7469787597656px;
    stroke-dasharray: 315.7469787597656px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 315.7469787597656px;
  }
}

@-webkit-keyframes animate-svg-fill-19 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

@keyframes animate-svg-fill-19 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

.svg-elem-19 {
  -webkit-animation: animate-svg-stroke-19 5s linear 2.16s both,
                       animate-svg-fill-19 1s ease 2.6s both;
          animation: animate-svg-stroke-19 5s linear 2.16s both,
               animate-svg-fill-19 1s ease 2.6s both;
}

@-webkit-keyframes animate-svg-stroke-20 {
  0% {
    stroke-dashoffset: 127.97068786621094px;
    stroke-dasharray: 127.97068786621094px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 127.97068786621094px;
  }
}

@keyframes animate-svg-stroke-20 {
  0% {
    stroke-dashoffset: 127.97068786621094px;
    stroke-dasharray: 127.97068786621094px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 127.97068786621094px;
  }
}

@-webkit-keyframes animate-svg-fill-20 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

@keyframes animate-svg-fill-20 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

.svg-elem-20 {
  -webkit-animation: animate-svg-stroke-20 5s linear 2.28s both,
                       animate-svg-fill-20 1s ease 2.7s both;
          animation: animate-svg-stroke-20 5s linear 2.28s both,
               animate-svg-fill-20 1s ease 2.7s both;
}

@-webkit-keyframes animate-svg-stroke-21 {
  0% {
    stroke-dashoffset: 127.94143676757812px;
    stroke-dasharray: 127.94143676757812px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 127.94143676757812px;
  }
}

@keyframes animate-svg-stroke-21 {
  0% {
    stroke-dashoffset: 127.94143676757812px;
    stroke-dasharray: 127.94143676757812px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 127.94143676757812px;
  }
}

@-webkit-keyframes animate-svg-fill-21 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

@keyframes animate-svg-fill-21 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

.svg-elem-21 {
  -webkit-animation: animate-svg-stroke-21 5s linear 2.4s both, animate-svg-fill-21 1s ease 2.8s both;
          animation: animate-svg-stroke-21 5s linear 2.4s both, animate-svg-fill-21 1s ease 2.8s both;
}

@-webkit-keyframes animate-svg-stroke-22 {
  0% {
    stroke-dashoffset: 127.9320068359375px;
    stroke-dasharray: 127.9320068359375px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 127.9320068359375px;
  }
}

@keyframes animate-svg-stroke-22 {
  0% {
    stroke-dashoffset: 127.9320068359375px;
    stroke-dasharray: 127.9320068359375px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 127.9320068359375px;
  }
}

@-webkit-keyframes animate-svg-fill-22 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

@keyframes animate-svg-fill-22 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

.svg-elem-22 {
  -webkit-animation: animate-svg-stroke-22 5s linear 2.52s both,
                       animate-svg-fill-22 1s ease 2.9000000000000004s both;
          animation: animate-svg-stroke-22 5s linear 2.52s both,
               animate-svg-fill-22 1s ease 2.9000000000000004s both;
}

@-webkit-keyframes animate-svg-stroke-23 {
  0% {
    stroke-dashoffset: 16.684043884277344px;
    stroke-dasharray: 16.684043884277344px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 16.684043884277344px;
  }
}

@keyframes animate-svg-stroke-23 {
  0% {
    stroke-dashoffset: 16.684043884277344px;
    stroke-dasharray: 16.684043884277344px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 16.684043884277344px;
  }
}

@-webkit-keyframes animate-svg-fill-23 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

@keyframes animate-svg-fill-23 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

.svg-elem-23 {
  -webkit-animation: animate-svg-stroke-23 5s linear 2.6399999999999997s both,
                       animate-svg-fill-23 1s ease 3s both;
          animation: animate-svg-stroke-23 5s linear 2.6399999999999997s both,
               animate-svg-fill-23 1s ease 3s both;
}

@-webkit-keyframes animate-svg-stroke-24 {
  0% {
    stroke-dashoffset: 90.92501068115234px;
    stroke-dasharray: 90.92501068115234px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 90.92501068115234px;
  }
}

@keyframes animate-svg-stroke-24 {
  0% {
    stroke-dashoffset: 90.92501068115234px;
    stroke-dasharray: 90.92501068115234px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 90.92501068115234px;
  }
}

@-webkit-keyframes animate-svg-fill-24 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

@keyframes animate-svg-fill-24 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

.svg-elem-24 {
  -webkit-animation: animate-svg-stroke-24 5s linear 2.76s both,
                       animate-svg-fill-24 1s ease 3.1000000000000005s both;
          animation: animate-svg-stroke-24 5s linear 2.76s both,
               animate-svg-fill-24 1s ease 3.1000000000000005s both;
}

@-webkit-keyframes animate-svg-stroke-25 {
  0% {
    stroke-dashoffset: 88.24002075195312px;
    stroke-dasharray: 88.24002075195312px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 88.24002075195312px;
  }
}

@keyframes animate-svg-stroke-25 {
  0% {
    stroke-dashoffset: 88.24002075195312px;
    stroke-dasharray: 88.24002075195312px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 88.24002075195312px;
  }
}

@-webkit-keyframes animate-svg-fill-25 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

@keyframes animate-svg-fill-25 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

.svg-elem-25 {
  -webkit-animation: animate-svg-stroke-25 5s linear 2.88s both,
                       animate-svg-fill-25 1s ease 3.2s both;
          animation: animate-svg-stroke-25 5s linear 2.88s both,
               animate-svg-fill-25 1s ease 3.2s both;
}

@-webkit-keyframes animate-svg-stroke-26 {
  0% {
    stroke-dashoffset: 51.3211784362793px;
    stroke-dasharray: 51.3211784362793px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 51.3211784362793px;
  }
}

@keyframes animate-svg-stroke-26 {
  0% {
    stroke-dashoffset: 51.3211784362793px;
    stroke-dasharray: 51.3211784362793px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 51.3211784362793px;
  }
}

@-webkit-keyframes animate-svg-fill-26 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

@keyframes animate-svg-fill-26 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

.svg-elem-26 {
  -webkit-animation: animate-svg-stroke-26 5s linear 3s both, animate-svg-fill-26 1s ease 3.3s both;
          animation: animate-svg-stroke-26 5s linear 3s both, animate-svg-fill-26 1s ease 3.3s both;
}

@-webkit-keyframes animate-svg-stroke-27 {
  0% {
    stroke-dashoffset: 100.82069396972656px;
    stroke-dasharray: 100.82069396972656px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 100.82069396972656px;
  }
}

@keyframes animate-svg-stroke-27 {
  0% {
    stroke-dashoffset: 100.82069396972656px;
    stroke-dasharray: 100.82069396972656px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 100.82069396972656px;
  }
}

@-webkit-keyframes animate-svg-fill-27 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

@keyframes animate-svg-fill-27 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

.svg-elem-27 {
  -webkit-animation: animate-svg-stroke-27 5s linear 3.12s both,
                       animate-svg-fill-27 1s ease 3.4000000000000004s both;
          animation: animate-svg-stroke-27 5s linear 3.12s both,
               animate-svg-fill-27 1s ease 3.4000000000000004s both;
}

@-webkit-keyframes animate-svg-stroke-28 {
  0% {
    stroke-dashoffset: 94.95100402832031px;
    stroke-dasharray: 94.95100402832031px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 94.95100402832031px;
  }
}

@keyframes animate-svg-stroke-28 {
  0% {
    stroke-dashoffset: 94.95100402832031px;
    stroke-dasharray: 94.95100402832031px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 94.95100402832031px;
  }
}

@-webkit-keyframes animate-svg-fill-28 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

@keyframes animate-svg-fill-28 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

.svg-elem-28 {
  -webkit-animation: animate-svg-stroke-28 5s linear 3.2399999999999998s both,
                       animate-svg-fill-28 1s ease 3.5s both;
          animation: animate-svg-stroke-28 5s linear 3.2399999999999998s both,
               animate-svg-fill-28 1s ease 3.5s both;
}

@-webkit-keyframes animate-svg-stroke-29 {
  0% {
    stroke-dashoffset: 103.37100219726562px;
    stroke-dasharray: 103.37100219726562px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 103.37100219726562px;
  }
}

@keyframes animate-svg-stroke-29 {
  0% {
    stroke-dashoffset: 103.37100219726562px;
    stroke-dasharray: 103.37100219726562px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 103.37100219726562px;
  }
}

@-webkit-keyframes animate-svg-fill-29 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

@keyframes animate-svg-fill-29 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

.svg-elem-29 {
  -webkit-animation: animate-svg-stroke-29 5s linear 3.36s both,
                       animate-svg-fill-29 1s ease 3.6000000000000005s both;
          animation: animate-svg-stroke-29 5s linear 3.36s both,
               animate-svg-fill-29 1s ease 3.6000000000000005s both;
}

@-webkit-keyframes animate-svg-stroke-30 {
  0% {
    stroke-dashoffset: 80.2079849243164px;
    stroke-dasharray: 80.2079849243164px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 80.2079849243164px;
  }
}

@keyframes animate-svg-stroke-30 {
  0% {
    stroke-dashoffset: 80.2079849243164px;
    stroke-dasharray: 80.2079849243164px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 80.2079849243164px;
  }
}

@-webkit-keyframes animate-svg-fill-30 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

@keyframes animate-svg-fill-30 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

.svg-elem-30 {
  -webkit-animation: animate-svg-stroke-30 5s linear 3.48s both,
                       animate-svg-fill-30 1s ease 3.7s both;
          animation: animate-svg-stroke-30 5s linear 3.48s both,
               animate-svg-fill-30 1s ease 3.7s both;
}

@-webkit-keyframes animate-svg-stroke-31 {
  0% {
    stroke-dashoffset: 100.82243347167969px;
    stroke-dasharray: 100.82243347167969px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 100.82243347167969px;
  }
}

@keyframes animate-svg-stroke-31 {
  0% {
    stroke-dashoffset: 100.82243347167969px;
    stroke-dasharray: 100.82243347167969px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 100.82243347167969px;
  }
}

@-webkit-keyframes animate-svg-fill-31 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

@keyframes animate-svg-fill-31 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

.svg-elem-31 {
  -webkit-animation: animate-svg-stroke-31 5s linear 3.5999999999999996s both,
                       animate-svg-fill-31 1s ease 3.8s both;
          animation: animate-svg-stroke-31 5s linear 3.5999999999999996s both,
               animate-svg-fill-31 1s ease 3.8s both;
}

@-webkit-keyframes animate-svg-stroke-32 {
  0% {
    stroke-dashoffset: 102.27011108398438px;
    stroke-dasharray: 102.27011108398438px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 102.27011108398438px;
  }
}

@keyframes animate-svg-stroke-32 {
  0% {
    stroke-dashoffset: 102.27011108398438px;
    stroke-dasharray: 102.27011108398438px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 102.27011108398438px;
  }
}

@-webkit-keyframes animate-svg-fill-32 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

@keyframes animate-svg-fill-32 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

.svg-elem-32 {
  -webkit-animation: animate-svg-stroke-32 5s linear 3.7199999999999998s both,
                       animate-svg-fill-32 1s ease 3.9000000000000004s both;
          animation: animate-svg-stroke-32 5s linear 3.7199999999999998s both,
               animate-svg-fill-32 1s ease 3.9000000000000004s both;
}

@-webkit-keyframes animate-svg-stroke-33 {
  0% {
    stroke-dashoffset: 90.90632629394531px;
    stroke-dasharray: 90.90632629394531px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 90.90632629394531px;
  }
}

@keyframes animate-svg-stroke-33 {
  0% {
    stroke-dashoffset: 90.90632629394531px;
    stroke-dasharray: 90.90632629394531px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 90.90632629394531px;
  }
}

@-webkit-keyframes animate-svg-fill-33 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

@keyframes animate-svg-fill-33 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

.svg-elem-33 {
  -webkit-animation: animate-svg-stroke-33 5s linear 3.84s both, animate-svg-fill-33 1s ease 4s both;
          animation: animate-svg-stroke-33 5s linear 3.84s both, animate-svg-fill-33 1s ease 4s both;
}

@-webkit-keyframes animate-svg-stroke-34 {
  0% {
    stroke-dashoffset: 113.10826873779297px;
    stroke-dasharray: 113.10826873779297px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 113.10826873779297px;
  }
}

@keyframes animate-svg-stroke-34 {
  0% {
    stroke-dashoffset: 113.10826873779297px;
    stroke-dasharray: 113.10826873779297px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 113.10826873779297px;
  }
}

@-webkit-keyframes animate-svg-fill-34 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

@keyframes animate-svg-fill-34 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

.svg-elem-34 {
  -webkit-animation: animate-svg-stroke-34 5s linear 3.96s both,
                       animate-svg-fill-34 1s ease 4.1000000000000005s both;
          animation: animate-svg-stroke-34 5s linear 3.96s both,
               animate-svg-fill-34 1s ease 4.1000000000000005s both;
}

@-webkit-keyframes animate-svg-stroke-35 {
  0% {
    stroke-dashoffset: 16.68779945373535px;
    stroke-dasharray: 16.68779945373535px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 16.68779945373535px;
  }
}

@keyframes animate-svg-stroke-35 {
  0% {
    stroke-dashoffset: 16.68779945373535px;
    stroke-dasharray: 16.68779945373535px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 16.68779945373535px;
  }
}

@-webkit-keyframes animate-svg-fill-35 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

@keyframes animate-svg-fill-35 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

.svg-elem-35 {
  -webkit-animation: animate-svg-stroke-35 5s linear 4.08s both,
                       animate-svg-fill-35 1s ease 4.2s both;
          animation: animate-svg-stroke-35 5s linear 4.08s both,
               animate-svg-fill-35 1s ease 4.2s both;
}

@-webkit-keyframes animate-svg-stroke-36 {
  0% {
    stroke-dashoffset: 90.0034408569336px;
    stroke-dasharray: 90.0034408569336px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 90.0034408569336px;
  }
}

@keyframes animate-svg-stroke-36 {
  0% {
    stroke-dashoffset: 90.0034408569336px;
    stroke-dasharray: 90.0034408569336px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 90.0034408569336px;
  }
}

@-webkit-keyframes animate-svg-fill-36 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

@keyframes animate-svg-fill-36 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

.svg-elem-36 {
  -webkit-animation: animate-svg-stroke-36 5s linear 4.2s both, animate-svg-fill-36 1s ease 4.3s both;
          animation: animate-svg-stroke-36 5s linear 4.2s both, animate-svg-fill-36 1s ease 4.3s both;
}

@-webkit-keyframes animate-svg-stroke-37 {
  0% {
    stroke-dashoffset: 103.34983825683594px;
    stroke-dasharray: 103.34983825683594px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 103.34983825683594px;
  }
}

@keyframes animate-svg-stroke-37 {
  0% {
    stroke-dashoffset: 103.34983825683594px;
    stroke-dasharray: 103.34983825683594px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 103.34983825683594px;
  }
}

@-webkit-keyframes animate-svg-fill-37 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

@keyframes animate-svg-fill-37 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

.svg-elem-37 {
  -webkit-animation: animate-svg-stroke-37 5s linear 4.32s both,
                       animate-svg-fill-37 1s ease 4.4s both;
          animation: animate-svg-stroke-37 5s linear 4.32s both,
               animate-svg-fill-37 1s ease 4.4s both;
}

@-webkit-keyframes animate-svg-stroke-38 {
  0% {
    stroke-dashoffset: 124.7688217163086px;
    stroke-dasharray: 124.7688217163086px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 124.7688217163086px;
  }
}

@keyframes animate-svg-stroke-38 {
  0% {
    stroke-dashoffset: 124.7688217163086px;
    stroke-dasharray: 124.7688217163086px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 124.7688217163086px;
  }
}

@-webkit-keyframes animate-svg-fill-38 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

@keyframes animate-svg-fill-38 {
  0% {
    fill: transparent;
  }

  100% {
    fill: rgb(35, 31, 32);
  }
}

.svg-elem-38 {
  -webkit-animation: animate-svg-stroke-38 5s linear 4.4399999999999995s both,
                       animate-svg-fill-38 1s ease 4.5s both;
          animation: animate-svg-stroke-38 5s linear 4.4399999999999995s both,
               animate-svg-fill-38 1s ease 4.5s both;
}
// JavaScript Document